.TH "numeric/include/vccc/numeric Directory Reference" 3 "Fri Dec 18 2020" "VCCC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
numeric/include/vccc/numeric Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBaverage\&.hpp\fP"
.br
.ti -1c
.RI "file \fBlossless_div\&.hpp\fP"
.br
.ti -1c
.RI "file \fBnorm\&.hpp\fP"
.br
.ti -1c
.RI "file \fBstddev\&.hpp\fP"
.br
.ti -1c
.RI "file \fBsum\&.hpp\fP"
.br
.in -1c
