.TH "type_traits/include/vccc/type_traits/arity.hpp" 3 "Fri Dec 18 2020" "VCCC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
type_traits/include/vccc/type_traits/arity.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <type_traits>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBvccc::arity< T >\fP"
.br
.ti -1c
.RI "struct \fBvccc::arity< R(*)(Args\&.\&.\&.)>\fP"
.br
.ti -1c
.RI "struct \fBvccc::arity< R(C::*)(Args\&.\&.\&.)>\fP"
.br
.ti -1c
.RI "struct \fBvccc::arity< R(C::*)(Args\&.\&.\&.) const >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBvccc\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "template<typename T > using \fBvccc::arity_t\fP = typename arity< T >::type"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "template<typename T > constexpr unsigned \fBvccc::arity_v\fP = arity<T>::value"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VCCC from the source code\&.
