.TH "type_support/include/vccc/type_support/at.hpp" 3 "Fri Dec 18 2020" "VCCC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
type_support/include/vccc/type_support/at.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'vccc/type_support/detail/container_at\&.hpp'\fP
.br
\fC#include 'vccc/type_traits\&.hpp'\fP
.br
\fC#include 'opencv2/core/saturate\&.hpp'\fP
.br
\fC#include 'vccc/type_support/core\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBvccc::detail::bind_obj< Ts >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBvccc\fP"
.br
.ti -1c
.RI " \fBvccc::detail\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<std::size_t i, typename C , typename T > constexpr decltype(auto) \fBvccc::at\fP (const T &t)"
.br
.ti -1c
.RI "template<std::size_t i, std::size_t j, typename C , typename T > constexpr decltype(auto) \fBvccc::at\fP (const T &t)"
.br
.ti -1c
.RI "template<typename \&.\&.\&. Args> constexpr detail::bind_obj< Args\&.\&.\&. > \fBvccc::bind_at\fP (Args &&\&.\&.\&. args)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VCCC from the source code\&.
