.TH "type_support/include/vccc/type_support/back_emplace.hpp" 3 "Fri Dec 18 2020" "VCCC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
type_support/include/vccc/type_support/back_emplace.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <iterator>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBvccc::back_emplace_iterator< Container >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBvccc\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename Container > back_emplace_iterator< Container > \fBvccc::back_emplacer\fP (Container &container)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VCCC from the source code\&.
