.TH "type_traits/include/vccc/type_traits/bigger_type.hpp" 3 "Fri Dec 18 2020" "VCCC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
type_traits/include/vccc/type_traits/bigger_type.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <type_traits>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBvccc::bigger_type< T >\fP"
.br
.ti -1c
.RI "struct \fBvccc::bigger_type< T1, T2 >\fP"
.br
.ti -1c
.RI "struct \fBvccc::bigger_type< T1, T2, Ts\&.\&.\&. >\fP"
.br
.ti -1c
.RI "struct \fBvccc::signed_bigger_type< T >\fP"
.br
.ti -1c
.RI "struct \fBvccc::signed_bigger_type< T1, T2 >\fP"
.br
.ti -1c
.RI "struct \fBvccc::signed_bigger_type< T1, T2, Ts\&.\&.\&. >\fP"
.br
.ti -1c
.RI "struct \fBvccc::unsigned_bigger_type< T >\fP"
.br
.ti -1c
.RI "struct \fBvccc::unsigned_bigger_type< T1, T2 >\fP"
.br
.ti -1c
.RI "struct \fBvccc::unsigned_bigger_type< T1, T2, Ts\&.\&.\&. >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBvccc\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "template<typename \&.\&.\&. Ts> using \fBvccc::bigger_type_t\fP = typename bigger_type< Ts\&.\&.\&. >::type"
.br
.ti -1c
.RI "template<typename \&.\&.\&. Ts> using \fBvccc::signed_bigger_type_t\fP = typename signed_bigger_type< Ts\&.\&.\&. >::type"
.br
.ti -1c
.RI "template<typename \&.\&.\&. Ts> using \fBvccc::unsigned_bigger_type_t\fP = typename unsigned_bigger_type< Ts\&.\&.\&. >::type"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VCCC from the source code\&.
