.TH "high/include/vccc/high/functional.hpp" 3 "Fri Dec 18 2020" "VCCC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
high/include/vccc/high/functional.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'vccc/high/functional/invoke\&.hpp'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for VCCC from the source code\&.
