.TH "log/include/vccc/log/detail/ios.hpp" 3 "Fri Dec 18 2020" "VCCC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log/include/vccc/log/detail/ios.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'TargetConditionals\&.h'\fP
.br
\fC#include <syslog\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLOGV_IMPL\fP(\&.\&.\&.)"
.br
.ti -1c
.RI "#define \fBLOGD_IMPL\fP(\&.\&.\&.)"
.br
.ti -1c
.RI "#define \fBLOGI_IMPL\fP(\&.\&.\&.)"
.br
.ti -1c
.RI "#define \fBLOGW_IMPL\fP(\&.\&.\&.)"
.br
.ti -1c
.RI "#define \fBLOGE_IMPL\fP(\&.\&.\&.)"
.br
.ti -1c
.RI "#define \fBLOGF_IMPL\fP(\&.\&.\&.)"
.br
.ti -1c
.RI "#define \fBLOGS_IMPL\fP(\&.\&.\&.)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define LOGV_IMPL( \&.\&.\&.)"

.SS "#define LOGD_IMPL( \&.\&.\&.)"

.SS "#define LOGI_IMPL( \&.\&.\&.)"

.SS "#define LOGW_IMPL( \&.\&.\&.)"

.SS "#define LOGE_IMPL( \&.\&.\&.)"

.SS "#define LOGF_IMPL( \&.\&.\&.)"

.SS "#define LOGS_IMPL( \&.\&.\&.)"

.SH "Author"
.PP 
Generated automatically by Doxygen for VCCC from the source code\&.
