.TH "type_traits/include/vccc/type_traits/is_container.hpp" 3 "Fri Dec 18 2020" "VCCC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
type_traits/include/vccc/type_traits/is_container.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'vccc/type_traits/void_t\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBvccc::is_container< T, typename >\fP"
.br
.ti -1c
.RI "struct \fBvccc::is_container< T, void_t< decltype(std::declval< T >()\&.begin()), decltype(std::declval< T >()\&.end()), decltype(std::declval< T >()\&.size())> >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBvccc\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "template<typename T > using \fBvccc::is_container_t\fP = typename is_container< T >::type"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "template<typename T > constexpr auto \fBvccc::is_container_v\fP = is_container<T>::value"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VCCC from the source code\&.
