.TH "type_traits/include/vccc/type_traits/is_printable.hpp" 3 "Fri Dec 18 2020" "VCCC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
type_traits/include/vccc/type_traits/is_printable.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'vccc/type_traits/void_t\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBvccc::is_printable< T, typename >\fP"
.br
.ti -1c
.RI "struct \fBvccc::is_printable< T, void_t< decltype(std::cout<< std::declval< T >())> >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBvccc\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VCCC from the source code\&.
