.TH "type_traits/include/vccc/type_traits/iterable.hpp" 3 "Fri Dec 18 2020" "VCCC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
type_traits/include/vccc/type_traits/iterable.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'vccc/type_traits/are\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBvccc::is_iterator< T, typename >\fP"
.br
.ti -1c
.RI "struct \fBvccc::value >>< T >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBvccc\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "template<typename T > using \fBvccc::is_iterator_t\fP = typename is_iterator< T >::type"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "template<typename T > constexpr auto \fBvccc::is_iterator_v\fP = is_iterator<T>::value"
.br
.ti -1c
.RI "template<typename \&.\&.\&. Ts> constexpr auto \fBvccc::iterable\fP = are_v<is_iterator<Ts>\&.\&.\&.> || are_v<std::is_pointer<Ts>\&.\&.\&.>"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VCCC from the source code\&.
