.TH "log/include/vccc/log.hpp" 3 "Fri Dec 18 2020" "VCCC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log/include/vccc/log.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'vccc/log/pwd\&.hpp'\fP
.br
\fC#include 'vccc/log/log\&.hpp'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for VCCC from the source code\&.
