.TH "type_traits/include/vccc/type_traits/detail/lossless_type_int_division.hpp" 3 "Fri Dec 18 2020" "VCCC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
type_traits/include/vccc/type_traits/detail/lossless_type_int_division.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <type_traits>\fP
.br
\fC#include <algorithm>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBvccc::detail::lossless_type_int_division< T1, T2 >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBvccc\fP"
.br
.ti -1c
.RI " \fBvccc::detail\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "template<typename T1 , typename T2 > using \fBvccc::detail::lossless_type_int_division_t\fP = typename lossless_type_int_division< T1, T2 >::type"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VCCC from the source code\&.
