.TH "type_traits/include/vccc/type_traits/lossless_type.hpp" 3 "Fri Dec 18 2020" "VCCC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
type_traits/include/vccc/type_traits/lossless_type.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'vccc/type_traits/are\&.hpp'\fP
.br
\fC#include 'vccc/type_traits/bigger_type\&.hpp'\fP
.br
\fC#include 'vccc/type_traits/detail/lossless_type_int_division\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBvccc::lossless_type_add< T >\fP"
.br
.ti -1c
.RI "struct \fBvccc::lossless_type_add< T1, T2 >\fP"
.br
.ti -1c
.RI "struct \fBvccc::lossless_type_add< T1, T2, Ts\&.\&.\&. >\fP"
.br
.ti -1c
.RI "struct \fBvccc::lossless_type_mul< T >\fP"
.br
.ti -1c
.RI "struct \fBvccc::lossless_type_mul< T1, T2 >\fP"
.br
.ti -1c
.RI "struct \fBvccc::lossless_type_mul< T1, T2, Ts\&.\&.\&. >\fP"
.br
.ti -1c
.RI "struct \fBvccc::lossless_type_div< T >\fP"
.br
.ti -1c
.RI "struct \fBvccc::lossless_type_div< T1, T2 >\fP"
.br
.ti -1c
.RI "struct \fBvccc::lossless_type_div< T1, T2, Ts\&.\&.\&. >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBvccc\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "template<typename \&.\&.\&. Types> using \fBvccc::decay_if_float_t\fP = typename std::conditional_t< are_< std::is_same< Types, float >\&.\&.\&. >::value, float, double >"
.br
.ti -1c
.RI "template<typename \&.\&.\&. Ts> using \fBvccc::lossless_type_add_t\fP = typename lossless_type_add< Ts\&.\&.\&. >::type"
.br
.ti -1c
.RI "template<typename \&.\&.\&. Ts> using \fBvccc::lossless_type_mul_t\fP = typename lossless_type_mul< Ts\&.\&.\&. >::type"
.br
.ti -1c
.RI "template<typename \&.\&.\&. Ts> using \fBvccc::lossless_type_div_t\fP = typename lossless_type_div< Ts\&.\&.\&. >::type"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VCCC from the source code\&.
