.TH "numeric/include/vccc/numeric/lossless_div.hpp" 3 "Fri Dec 18 2020" "VCCC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
numeric/include/vccc/numeric/lossless_div.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'vccc/type_traits\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBvccc\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T1 , typename T2 > decltype(auto) \fBvccc::lossless_div\fP (const T1 a, const T2 b)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VCCC from the source code\&.
