.TH "type_traits/include/vccc/type_traits/numeric.hpp" 3 "Fri Dec 18 2020" "VCCC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
type_traits/include/vccc/type_traits/numeric.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <type_traits>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBvccc::multiples_of< T, A, B >\fP"
.br
.ti -1c
.RI "struct \fBvccc::is_odd< T, A >\fP"
.br
.ti -1c
.RI "struct \fBvccc::is_even< T, A >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBvccc\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "template<typename T , T A, T B> using \fBvccc::multiples_of_t\fP = typename multiples_of< T, A, B >::type"
.br
.ti -1c
.RI "template<typename T , T A> using \fBvccc::is_odd_t\fP = typename is_odd< T, A >::type"
.br
.ti -1c
.RI "template<typename T , T A> using \fBvccc::is_even_t\fP = typename is_even< T, A >::type"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "template<typename T , T A, T B> constexpr bool \fBvccc::multiples_of_v\fP = multiples_of<T, A, B>::value"
.br
.ti -1c
.RI "template<typename T , T A> constexpr bool \fBvccc::is_odd_v\fP = is_odd<T, A>::value"
.br
.ti -1c
.RI "template<typename T , T A> constexpr bool \fBvccc::is_even_v\fP = is_even<T, A>::value"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VCCC from the source code\&.
