.TH "random/include/vccc/random/pick.hpp" 3 "Fri Dec 18 2020" "VCCC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
random/include/vccc/random/pick.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <unordered_set>\fP
.br
\fC#include <random>\fP
.br
\fC#include <type_traits>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBvccc\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , typename Container  = std::unordered_set<T>, typename RandomGenerator > Container \fBvccc::pick_k\fP (T a, T b, T k, RandomGenerator &&gen)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VCCC from the source code\&.
