.TH "numeric/include/vccc/numeric/stddev.hpp" 3 "Fri Dec 18 2020" "VCCC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
numeric/include/vccc/numeric/stddev.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'vccc/numeric/average\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBvccc\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename InputIterator , typename T , VCCC_REQUIRE(iterable< InputIterator >) > auto \fBvccc::stddev\fP (InputIterator first, InputIterator last, T avg)"
.br
.ti -1c
.RI "template<typename InputIterator , VCCC_REQUIRE(iterable< InputIterator >) > auto \fBvccc::stddev\fP (InputIterator first, InputIterator last)"
.br
.ti -1c
.RI "template<typename \&.\&.\&. Numbers, VCCC_REQUIRE(!iterable< Numbers\&.\&.\&. >) > auto \fBvccc::stddev\fP (Numbers\&.\&.\&. numbers)"
.br
.ti -1c
.RI "template<typename InputIterator > constexpr auto \fBvccc::avg_stddev\fP (InputIterator first, InputIterator last)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VCCC from the source code\&.
