.TH "utility/include/vccc/utility/time.hpp" 3 "Fri Dec 18 2020" "VCCC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
utility/include/vccc/utility/time.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <chrono>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBvccc\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T > auto \fBvccc::getCurrentTime\fP ()"
.br
.ti -1c
.RI "decltype(auto) \fBvccc::getCurrentMilliseconds\fP ()"
.br
.ti -1c
.RI "decltype(auto) \fBvccc::getCurrentMicroseconds\fP ()"
.br
.ti -1c
.RI "decltype(auto) \fBvccc::getCurrentNanoseconds\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VCCC from the source code\&.
