.TH "vccc::detail::cv_size< cv::Matx< T, m, n > >" 3 "Fri Dec 18 2020" "VCCC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vccc::detail::cv_size< cv::Matx< T, m, n > >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cv_mat\&.hpp>\fP
.PP
Inherits \fBvccc::detail::cv_size_n< m *n >\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<typename T, int m, int n>
.br
struct vccc::detail::cv_size< cv::Matx< T, m, n > >"
\fBcv_size\fP 

.SH "Author"
.PP 
Generated automatically by Doxygen for VCCC from the source code\&.
