.TH "vccc::is_specialization< Ref< Args... >, Ref >" 3 "Fri Dec 18 2020" "VCCC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vccc::is_specialization< Ref< Args... >, Ref >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <is_specialization\&.hpp>\fP
.PP
Inherits true_type\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VCCC from the source code\&.
