.TH "vccc::lossless_type_div< T1, T2, Ts... >" 3 "Fri Dec 18 2020" "VCCC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vccc::lossless_type_div< T1, T2, Ts... >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lossless_type\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBtype\fP = decltype(static_cast< \fBlossless_type_div_t\fP< T1, T2 > >(0)/static_cast< \fBlossless_type_div_t\fP< Ts\&.\&.\&. > >(0))"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename T1 , typename T2 , typename \&.\&.\&. Ts> using \fBvccc::lossless_type_div\fP< T1, T2, Ts\&.\&.\&. >::\fBtype\fP =  decltype(static_cast<\fBlossless_type_div_t\fP<T1, T2> >(0) / static_cast<\fBlossless_type_div_t\fP<Ts\&.\&.\&.> >(0))"


.SH "Author"
.PP 
Generated automatically by Doxygen for VCCC from the source code\&.
