.TH "vccc::are_< Conds >" 3 "Fri Dec 18 2020" "VCCC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vccc::are_< Conds >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <are\&.hpp>\fP
.PP
Inherits true_type\&.
.SH "Detailed Description"
.PP 

.SS "template<typename\&.\&.\&. Conds>
.br
struct vccc::are_< Conds >"
are 

.SH "Author"
.PP 
Generated automatically by Doxygen for VCCC from the source code\&.
