.TH "vccc::detail::cv_size< cv::Vec< T, cn > >" 3 "Fri Dec 18 2020" "VCCC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vccc::detail::cv_size< cv::Vec< T, cn > >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cv_vec\&.hpp>\fP
.PP
Inherits \fBvccc::detail::cv_size_n< cn >\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<typename T, int cn>
.br
struct vccc::detail::cv_size< cv::Vec< T, cn > >"
\fBcv_size\fP 

.SH "Author"
.PP 
Generated automatically by Doxygen for VCCC from the source code\&.
