.TH "vccc::lossless_type_add< T >" 3 "Fri Dec 18 2020" "VCCC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vccc::lossless_type_add< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lossless_type\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBtype\fP = T"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename T > using \fBvccc::lossless_type_add\fP< T >::\fBtype\fP =  T"


.SH "Author"
.PP 
Generated automatically by Doxygen for VCCC from the source code\&.
