.TH "vccc::are_scalar< Ts >" 3 "Fri Dec 18 2020" "VCCC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vccc::are_scalar< Ts >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <are\&.hpp>\fP
.PP
Inherits \fBvccc::are_< std::is_scalar< Ts >\&.\&.\&. >\fP\&.
.SH "Detailed Description"
.PP 

.SS "template<typename \&.\&.\&. Ts>
.br
struct vccc::are_scalar< Ts >"
\fBare_scalar\fP 

.SH "Author"
.PP 
Generated automatically by Doxygen for VCCC from the source code\&.
