.TH "vccc::lossless_type_div< T1, T2 >" 3 "Fri Dec 18 2020" "VCCC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vccc::lossless_type_div< T1, T2 >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lossless_type\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBtype\fP = std::conditional_t< \fBare_integral_v\fP< T1, T2 >, \fBdetail::lossless_type_int_division_t\fP< T1, T2 >, decltype(static_cast< \fBlossless_type_div_t\fP< T1 > >(0)/static_cast< \fBlossless_type_div_t\fP< T2 > >(0))>"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename T1 , typename T2 > using \fBvccc::lossless_type_div\fP< T1, T2 >::\fBtype\fP =  std::conditional_t<\fBare_integral_v\fP<T1, T2>, \fBdetail::lossless_type_int_division_t\fP<T1, T2>, decltype(static_cast<\fBlossless_type_div_t\fP<T1> >(0) / static_cast<\fBlossless_type_div_t\fP<T2> >(0))>"


.SH "Author"
.PP 
Generated automatically by Doxygen for VCCC from the source code\&.
