.TH "vccc::signed_bigger_type<... >" 3 "Fri Dec 18 2020" "VCCC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vccc::signed_bigger_type<... >
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.SS "template<typename \&.\&.\&.>
.br
struct vccc::signed_bigger_type<\&.\&.\&. >"
returns signed bigger type of Ts if unsigned types are provided, smaller unsigned types will be returned 

.SH "Author"
.PP 
Generated automatically by Doxygen for VCCC from the source code\&.
