.TH "vccc::is_container< T, typename >" 3 "Fri Dec 18 2020" "VCCC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vccc::is_container< T, typename >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <is_container\&.hpp>\fP
.PP
Inherits false_type\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VCCC from the source code\&.
