.TH "vccc::arity< R(C::*)(Args...)>" 3 "Fri Dec 18 2020" "VCCC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vccc::arity< R(C::*)(Args...)>
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <arity\&.hpp>\fP
.PP
Inherits integral_constant< unsigned, sizeof\&.\&.\&.(Args)>\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VCCC from the source code\&.
