.TH "vccc::lossless_type_div<... >" 3 "Fri Dec 18 2020" "VCCC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vccc::lossless_type_div<... >
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.SS "template<typename\&.\&.\&.>
.br
struct vccc::lossless_type_div<\&.\&.\&. >"
\fBlossless_type_div\fP 

.SH "Author"
.PP 
Generated automatically by Doxygen for VCCC from the source code\&.
