.TH "vccc::is_printable< T, void_t< decltype(std::cout<< std::declval< T >())> >" 3 "Fri Dec 18 2020" "VCCC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vccc::is_printable< T, void_t< decltype(std::cout<< std::declval< T >())> >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <is_printable\&.hpp>\fP
.PP
Inherits true_type\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VCCC from the source code\&.
