.TH "vccc::impl" 3 "Fri Dec 18 2020" "VCCC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vccc::impl
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename Arg > constexpr auto \fBsumImpl\fP (const Arg &arg)"
.br
.ti -1c
.RI "template<typename Arg1 , typename Arg2 > constexpr auto \fBsumImpl\fP (const Arg1 &arg1, const Arg2 &arg2)"
.br
.ti -1c
.RI "template<typename Arg , typename \&.\&.\&. Args> constexpr auto \fBsumImpl\fP (const Arg &arg, const Args &\&.\&.\&. args)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<typename Arg > constexpr auto vccc::impl::sumImpl (const Arg & arg)\fC [constexpr]\fP"

.SS "template<typename Arg1 , typename Arg2 > constexpr auto vccc::impl::sumImpl (const Arg1 & arg1, const Arg2 & arg2)\fC [constexpr]\fP"

.SS "template<typename Arg , typename \&.\&.\&. Args> constexpr auto vccc::impl::sumImpl (const Arg & arg, const Args &\&.\&.\&. args)\fC [constexpr]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for VCCC from the source code\&.
