.TH "vccc::detail::cv_size< cv::Size_< T > >" 3 "Fri Dec 18 2020" "VCCC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vccc::detail::cv_size< cv::Size_< T > >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cv_size\&.hpp>\fP
.PP
Inherits \fBvccc::detail::cv_size_n< 2 >\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
struct vccc::detail::cv_size< cv::Size_< T > >"
\fBcv_size\fP 

.SH "Author"
.PP 
Generated automatically by Doxygen for VCCC from the source code\&.
