.TH "vccc::bigger_type<... >" 3 "Fri Dec 18 2020" "VCCC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vccc::bigger_type<... >
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.SS "template<typename \&.\&.\&.>
.br
struct vccc::bigger_type<\&.\&.\&. >"
returns bigger type 

.SH "Author"
.PP 
Generated automatically by Doxygen for VCCC from the source code\&.
