.TH "vccc::detail::lossless_type_int_division< T1, T2 >" 3 "Fri Dec 18 2020" "VCCC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vccc::detail::lossless_type_int_division< T1, T2 >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lossless_type_int_division\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBtype\fP = std::conditional_t< std::max(sizeof(T1), sizeof(T2))<=4, float, double >"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename T1 , typename T2 > using \fBvccc::detail::lossless_type_int_division\fP< T1, T2 >::\fBtype\fP =  std::conditional_t<std::max(sizeof(T1), sizeof(T2)) <= 4, float, double>"


.SH "Author"
.PP 
Generated automatically by Doxygen for VCCC from the source code\&.
