.TH "vccc::Logger" 3 "Fri Dec 18 2020" "VCCC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vccc::Logger
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <logger\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename \&.\&.\&. Args> \fBLogger\fP (const Args &\&.\&.\&. args)"
.br
.ti -1c
.RI "std::string \fBget\fP () const"
.br
.ti -1c
.RI "template<typename T > void \fBadd\fP (const T &n)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename \&.\&.\&. Args> vccc::Logger::Logger (const Args &\&.\&.\&. args)"

.SH "Member Function Documentation"
.PP 
.SS "std::string vccc::Logger::get () const\fC [inline]\fP"

.SS "template<typename T > void vccc::Logger::add (const T & n)"


.SH "Author"
.PP 
Generated automatically by Doxygen for VCCC from the source code\&.
