.TH "utility/CMakeLists.txt" 3 "Fri Dec 18 2020" "VCCC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
utility/CMakeLists.txt
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBcmake_minimum_required\fP (VERSION 3\&.5\&.\&.\&.3\&.16) project(vccc_utility VERSION '$"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "cmake_minimum_required (VERSION 3\&.5\&.\&.\&.3\&. 16)"

.SH "Author"
.PP 
Generated automatically by Doxygen for VCCC from the source code\&.
