.TH "type_support/include/vccc/type_support/detail/container_at.hpp" 3 "Fri Dec 18 2020" "VCCC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
type_support/include/vccc/type_support/detail/container_at.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'vccc/type_traits\&.hpp'\fP
.br
\fC#include 'vccc/utility\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBvccc\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<std::size_t i, typename Container , VCCC_REQUIRE(is_container_v< Container >) > decltype(auto) \fBvccc::at\fP (Container &container)"
.br
.ti -1c
.RI "template<std::size_t i, typename Container , VCCC_REQUIRE(is_container_v< Container >) > decltype(auto) \fBvccc::at\fP (const Container &container)"
.br
.ti -1c
.RI "template<std::size_t i, typename Container , VCCC_REQUIRE(is_container_v< Container >) > decltype(auto) \fBvccc::at\fP (Container &&container)"
.br
.ti -1c
.RI "template<std::size_t i, typename Container , VCCC_REQUIRE(is_container_v< Container >) > decltype(auto) \fBvccc::at\fP (const Container &&container)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VCCC from the source code\&.
