.TH "type_support/include/vccc/type_support/detail/convert_to.hpp" 3 "Fri Dec 18 2020" "VCCC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
type_support/include/vccc/type_support/detail/convert_to.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <utility>\fP
.br
\fC#include 'vccc/utility\&.hpp'\fP
.br
\fC#include 'vccc/type_support/at\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBvccc\fP"
.br
.ti -1c
.RI " \fBvccc::detail\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename R , typename T , std::size_t\&.\&.\&. I, typename IT , IT\&.\&.\&. I2> R \fBvccc::detail::fill_rest\fP (const T &from, std::index_sequence< I\&.\&.\&. > index_seq, std::integer_sequence< IT, I2\&.\&.\&. > rest_seq)"
.br
.ti -1c
.RI "template<typename R , typename T , std::size_t\&.\&.\&. I> R \fBvccc::detail::convert_to_impl\fP (std::true_type, const T &from, std::index_sequence< I\&.\&.\&. > index_seq)"
.br
.ti -1c
.RI "template<typename R , typename T , std::size_t\&.\&.\&. I> R \fBvccc::detail::convert_to_impl\fP (std::false_type, const T &from, std::index_sequence< I\&.\&.\&. >)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VCCC from the source code\&.
