.TH "high/include/vccc/high/functional/invoke.hpp" 3 "Fri Dec 18 2020" "VCCC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
high/include/vccc/high/functional/invoke.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'vccc/high/functional/detail/invoke\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBvccc\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<class F , class\&.\&.\&. Args> constexpr decltype(auto) \fBvccc::invoke\fP (F &&f, Args &&\&.\&.\&. args)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VCCC from the source code\&.
