.TH "log/include/vccc/log/logger.hpp" 3 "Fri Dec 18 2020" "VCCC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log/include/vccc/log/logger.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <regex>\fP
.br
\fC#include 'vccc/log/detail/c_printable\&.hpp'\fP
.br
\fC#include 'vccc/log/detail/custom_ostream\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBvccc::Logger\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBvccc\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBvccc::c_printable\fP = std::true_type"
.br
.ti -1c
.RI "using \fBvccc::not_c_printable\fP = std::false_type"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VCCC from the source code\&.
