.TH "md__r_e_a_d_m_e" 3 "Fri Dec 18 2020" "VCCC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__r_e_a_d_m_e \- VCCC 

.SH "VisualCamp Common C++ library"
.PP
.IP "\(bu" 2
Requires C++14 or above
.PP
.SS "<tt>high</tt>"
Standalone
.IP "\(bu" 2
\fCfunctional\fP
.IP "  \(bu" 4
\fCinvoke\fP
.PP

.IP "\(bu" 2
\fCtuple\fP
.IP "  \(bu" 4
\fCapply\fP
.PP

.PP
.SS "<tt>literal</tt>"
Standalone
.IP "\(bu" 2
\fC_format\fP
.IP "\(bu" 2
\fCFormatter\fP
.PP
.SS "<tt>type_traits</tt>"
Standalone 
.br
.IP "\(bu" 2
\fCare_\fP, \fCare_\&.\&.\&.\fP
.IP "\(bu" 2
\fCvtype_t\fP, \fCvoid_t\fP, \fCis_iterator\fP, \fCiterable\fP, \fCis_specialization\fP, \fCis_container\fP, \fCis_printable\fP, \fCis_std_array\fP
.IP "\(bu" 2
\fCbigger_type\fP, \fCsigned_bigger_type\fP, \fCunsigned_bigger_type\fP
.IP "\(bu" 2
\fCVCCC_REQUIRE\fP, \fCVCCC_REQUIRE_FORWARD\fP, \fCVCCC_REQUIRE_IMPL\fP
.IP "\(bu" 2
\fCmultiples_of\fP, \fCis_odd\fP, \fCis_even\fP
.IP "\(bu" 2
\fClossless_type_add\fP, \fClossless_type_mul\fP, \fClossless_type_div\fP
.PP
.SS "<tt>log</tt>"
Requires \fCtype_traits\fP 
.br
.IP "\(bu" 2
\fCLOGD\fP, \fCLOGE\fP, \&.\&.\&.
.IP "\(bu" 2
\fCPWD\fP
.PP
.SS "<tt>math</tt>"
Requires \fCtype_traits\fP
.IP "\(bu" 2
\fCgradient\fP
.IP "\(bu" 2
\fCpartial_diff\fP
.IP "\(bu" 2
\fCepsilon\fP
.PP
.SS "<tt>numeric</tt>"
Requires \fCtype_traits\fP 
.br
.IP "\(bu" 2
\fCaverage\fP
.IP "\(bu" 2
\fClossless_div\fP
.IP "\(bu" 2
\fCnorm\fP
.IP "\(bu" 2
\fCstddev\fP, \fCavg_stddev\fP
.IP "\(bu" 2
\fCsum\fP, \fCsquare\fP, \fCsquare_sum\fP
.PP
.SS "<tt>random</tt>"
Standalone
.IP "\(bu" 2
\fCrandom_sample\fP, \fCpick_k\fP
.PP
.SS "<tt>range</tt>"
Standalone
.IP "\(bu" 2
\fCrange\fP
.PP
.SS "<tt>utility</tt>"
Standalone 
.br
.IP "\(bu" 2
\fCmake_rindex_sequence\fP, \fCmake_same_sequence\fP, \fCmake_zero_sequence\fP, \fCmake_range_sequence\fP
.IP "\(bu" 2
\fCgetCurrentMilliseconds\fP, \fCgetCurrentMicroseconds\fP, \fCgetCurrentNanoseconds\fP
.IP "\(bu" 2
\fCEXPECTS\fP, \fCENSURES\fP, \fCBOUNDS_ASSERT\fP, \fCALWAYS_ASSERT\fP
.PP
.SS "<tt>type_support</tt>"
Requires \fCOpenCV\fP, \fCtype_traits\fP, \fCutility\fP
.IP "\(bu" 2
\fCat\fP, \fCbind_at\fP
.IP "\(bu" 2
\fCback_emplacer\fP
.IP "\(bu" 2
\fCconvert_to\fP
.IP "\(bu" 2
\fCvtype_convert\fP
.IP "\(bu" 2
\fCresize\fP
.IP "\(bu" 2
\fCadd\fP
.IP "\(bu" 2
\fCreserved_vector\fP 
.PP

