.TH "log/include/vccc/log/detail/print.hpp" 3 "Fri Dec 18 2020" "VCCC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log/include/vccc/log/detail/print.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'vccc/type_traits\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBvccc\fP"
.br
.ti -1c
.RI " \fBvccc::detail\fP"
.br
.ti -1c
.RI " \fBvccc::detail::impl\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename \&.\&.\&. Args> std::ostream & \fBvccc::operator<<\fP (std::ostream &os, const std::tuple< Args\&.\&.\&. > &tup)"
.br
.ti -1c
.RI "template<typename \&.\&.\&. Args> std::ostream & \fBvccc::operator<<\fP (std::ostream &os, const std::pair< Args\&.\&.\&. > &tup)"
.br
.ti -1c
.RI "template<typename T , T\&.\&.\&. I> std::ostream & \fBvccc::operator<<\fP (std::ostream &os, const std::integer_sequence< T, I\&.\&.\&. > &seq)"
.br
.ti -1c
.RI "template<typename T , VCCC_REQUIRE_IMPL(is_container< T >::value &&!is_printable< T >::value) > std::ostream & \fBvccc::operator<<\fP (std::ostream &os, const T &v)"
.br
.ti -1c
.RI "template<typename Iterator > std::ostream & \fBvccc::detail::print_iterator\fP (std::ostream &os, Iterator first, Iterator last)"
.br
.ti -1c
.RI "template<typename Tuple , std::size_t \&.\&.\&. I> std::ostream & \fBvccc::detail::print_tuple\fP (std::ostream &os, const Tuple &tup, std::index_sequence< 0, I\&.\&.\&. >)"
.br
.ti -1c
.RI "template<typename Arg > void \fBvccc::detail::impl::print_multiples_impl\fP (std::ostream &os, const Arg &arg)"
.br
.ti -1c
.RI "template<typename Arg , typename \&.\&.\&. Args> void \fBvccc::detail::impl::print_multiples_impl\fP (std::ostream &os, const Arg &arg, const Args &\&.\&.\&. args)"
.br
.ti -1c
.RI "template<typename \&.\&.\&. Args> void \fBvccc::detail::print_multiples\fP (std::ostream &os, const Args &\&.\&.\&. args)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VCCC from the source code\&.
