.TH "random/include/vccc/random.hpp" 3 "Fri Dec 18 2020" "VCCC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
random/include/vccc/random.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'vccc/random/pick\&.hpp'\fP
.br
\fC#include 'vccc/random/sample\&.hpp'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for VCCC from the source code\&.
