.TH "type_support/include/vccc/type_support/std/tuple.hpp" 3 "Fri Dec 18 2020" "VCCC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
type_support/include/vccc/type_support/std/tuple.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <tuple>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBvccc\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<std::size_t i, typename T , std::enable_if_t<(i< std::tuple_size< T >::value), int >  = 0> constexpr decltype(auto) \fBvccc::at\fP (T &tup)"
.br
.ti -1c
.RI "template<std::size_t i, typename C , typename T > constexpr decltype(auto) \fBvccc::at\fP (const T &t)"
.br
.ti -1c
.RI "template<std::size_t i, typename T , std::enable_if_t<(i< std::tuple_size< T >::value), int >  = 0> constexpr decltype(auto) \fBvccc::at\fP (T &&tup)"
.br
.ti -1c
.RI "template<std::size_t i, typename T , std::enable_if_t<(i< std::tuple_size< T >::value), int >  = 0> constexpr decltype(auto) \fBvccc::at\fP (const T &&tup)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VCCC from the source code\&.
