.TH "vccc::is_odd< T, A >" 3 "Fri Dec 18 2020" "VCCC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vccc::is_odd< T, A >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <numeric\&.hpp>\fP
.PP
Inherits integral_constant< bool, A &1 >\&.
.SH "Detailed Description"
.PP 

.SS "template<typename T, T A>
.br
struct vccc::is_odd< T, A >"
\fBis_odd\fP 

.SH "Author"
.PP 
Generated automatically by Doxygen for VCCC from the source code\&.
