.TH "vccc::detail::are_types_c_printable< T >" 3 "Fri Dec 18 2020" "VCCC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vccc::detail::are_types_c_printable< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <c_printable\&.hpp>\fP
.PP
Inherits false_type\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VCCC from the source code\&.
