.TH "vccc::is_container< T, void_t< decltype(std::declval< T >().begin()), decltype(std::declval< T >().end()), decltype(std::declval< T >().size())> >" 3 "Fri Dec 18 2020" "VCCC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vccc::is_container< T, void_t< decltype(std::declval< T >().begin()), decltype(std::declval< T >().end()), decltype(std::declval< T >().size())> >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <is_container\&.hpp>\fP
.PP
Inherits true_type\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VCCC from the source code\&.
