.TH "vccc::detail::is_cv_type< T >" 3 "Fri Dec 18 2020" "VCCC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vccc::detail::is_cv_type< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cv_size\&.hpp>\fP
.PP
Inherits integral_constant< bool,(cv_size< T >::value > 0) >\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VCCC from the source code\&.
