.TH "vccc::are_arithmetic< Ts >" 3 "Fri Dec 18 2020" "VCCC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vccc::are_arithmetic< Ts >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <are\&.hpp>\fP
.PP
Inherits \fBvccc::are_< std::is_arithmetic< Ts >\&.\&.\&. >\fP\&.
.SH "Detailed Description"
.PP 

.SS "template<typename \&.\&.\&. Ts>
.br
struct vccc::are_arithmetic< Ts >"
\fBare_\fP helper of std::is_\&.\&.\&.<> \fBare_arithmetic\fP 

.SH "Author"
.PP 
Generated automatically by Doxygen for VCCC from the source code\&.
