.TH "vccc::detail::impl" 3 "Fri Dec 18 2020" "VCCC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vccc::detail::impl
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename Arg > void \fBprint_multiples_impl\fP (std::ostream &os, const Arg &arg)"
.br
.ti -1c
.RI "template<typename Arg , typename \&.\&.\&. Args> void \fBprint_multiples_impl\fP (std::ostream &os, const Arg &arg, const Args &\&.\&.\&. args)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<typename Arg > void vccc::detail::impl::print_multiples_impl (std::ostream & os, const Arg & arg)"

.SS "template<typename Arg , typename \&.\&.\&. Args> void vccc::detail::impl::print_multiples_impl (std::ostream & os, const Arg & arg, const Args &\&.\&.\&. args)"

.SH "Author"
.PP 
Generated automatically by Doxygen for VCCC from the source code\&.
