name: Ubuntu

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
      - develop
  page_build:
  release:
    types: # This configuration does not affect the page_build event above
      - created

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: [ self-hosted, linux ]

    strategy:
      matrix:
        cxx: [ 14, 17 ]

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: >
        cmake -B ${{github.workspace}}/build
        -DCMAKE_BUILD_TYPE=$BUILD_TYPE
        -DCMAKE_CXX_STANDARD=${{matrix.cxx}}
        -DVCCC_USE_OPENCV_FEATURES=OFF
        -DVCCC_RUN_TEST=ON
        -DVCCC_TEST_MATRIX=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -- -j 6

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C $BUILD_TYPE --extra-verbose --output-on-failure

    - name: Configure CMake(With OpenCV)
      run: >
        cmake -B ${{github.workspace}}/build-opencv
        -DCMAKE_BUILD_TYPE=$BUILD_TYPE
        -DCMAKE_CXX_STANDARD=${{matrix.cxx}}
        -DVCCC_TEST_SYSTEM_OPENCV=ON
        -DVCCC_RUN_TEST=ON
        -DVCCC_TEST_MATRIX=ON

    - name: Build(With OpenCV)
      run: cmake --build ${{github.workspace}}/build-opencv --config ${{env.BUILD_TYPE}} -- -j 6

    - name: Test(With OpenCV)
      working-directory: ${{github.workspace}}/build-opencv
      run: ctest -C $BUILD_TYPE --extra-verbose --output-on-failure
