name: MacOS

on:
  push:
    branches:
      - '**'
      - '!releases'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: [ self-hosted, macos ]

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: >
        cmake -B ${{github.workspace}}/build
        -DCMAKE_BUILD_TYPE=$BUILD_TYPE
        -DCMAKE_CXX_STANDARD=${{matrix.cxx}}
        -DVCCC_USE_OPENCV_FEATURES=OFF
        -DVCCC_RUN_TEST=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -- -j 2

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C $BUILD_TYPE --extra-verbose --output-on-failure
